### ISSUE TITLE
Permission denied while saving a file

### ISSUE THREAD

**Issue by Nefcanto** [linuxserver/docker-code-server#78] opened 2021-08-23 18:41 UTC
I ran an instance of your image inside a docker and launched VS Code at `localhost:8443`.

However, when I want to save a file, I see this error:

> Failed to save 'TicketController.cs': Unable to write file 'vscode-remote://0.0.0.0:8443/Company/AdminApi/Api/Controllers/TicketController.cs' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/Company/AdminApi/Api/Controllers/TicketController.cs')

**Comment by drizuid** [comment] 2021-12-21 00:26
Please fill out the full template

**Comment by drizuid** [comment] 2021-12-21 00:27
duplicate of https://github.com/linuxserver/docker-code-server/issues/79

**Closed by drizuid** 2021-12-21 00:27 UTC
Labels: invalid, no-issue-activity
