### ISSUE TITLE
Error message and unable to access the terminal

### ISSUE THREAD

**Issue by poundflag** [linuxserver/docker-code-server#143] opened 2023-02-18 12:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to access the terminal the message from the screenshot appears. I am not able to use the terminal in any way (Writing in it doesn‘t work).

![1011C9A3-1A97-435D-A41D-7A3541D222D0](https://user-images.githubusercontent.com/89596444/219864361-9a956db4-bfc2-4451-9abc-846fc32cc0a6.jpeg)

This is the first time I‘ve used Code-Server with docker so there may be a mistake on my part.
The following screenshots show my configuration as well as the version I am using.

![E791F432-B0EE-4777-949E-F62D58F74167](https://user-images.githubusercontent.com/89596444/219864358-d7c82c48-1b9a-4433-9c4b-dd4a4f6bc9eb.jpeg)
![8C06D7D8-9EBC-486F-9ECE-F3EC3C4212EF](https://user-images.githubusercontent.com/89596444/219864360-3f72cf11-7030-47f7-98fc-c97db4ea94eb.jpeg)

### Expected Behavior

It should open the bash terminal, any you should be able to use it.

### Steps To Reproduce

1. Click on the view button „Terminal“
2. Select „New Terminal“

### Environment

```markdown
- OS:Fedora 37
- How docker service was installed: With the following guide https://docs.docker.com/engine/install/fedora/
```

### CPU architecture

x86-64

### Docker creation

```bash
Is in the screenshot
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

setting up sudo access
adding abc to sudoers
setting sudo password using SUDO_PASSWORD env var
[custom-init] No custom files found, skipping...
starting with no password
[2023-02-18T11:03:06.787Z] info  code-server 4.10.0 ac1fba8bde0c3f29bf6bc27d3d7d75cb2390a7c2
[2023-02-18T11:03:06.792Z] info  Using user-data-dir ~/data
[2023-02-18T11:03:06.814Z] info  Using config file ~/.config/code-server/config.yaml
[2023-02-18T11:03:06.816Z] info  HTTP server listening on http://0.0.0.0:8443/
[2023-02-18T11:03:06.817Z] info    - Authentication is disabled
[2023-02-18T11:03:06.817Z] info    - Not serving HTTPS
[2023-02-18T11:03:06.818Z] info    - Proxying the following domain:
[2023-02-18T11:03:06.819Z] info      - *.code-server.my.domain
[ls.io-init] done.
[11:03:13] 




[11:03:13] Extension host agent started.
[11:03:15] [172.18.0.1][2bd753e4][ManagementConnection] New connection established.
[11:03:17] [172.18.0.1][2e7d1b2b][ExtensionHostConnection] New connection established.
[11:03:17] [172.18.0.1][2e7d1b2b][ExtensionHostConnection] <216> Launched Extension Host Process.
[migrations] started
[migrations] no migrations found
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

setting up sudo access
setting sudo password using SUDO_PASSWORD env var
[custom-init] No custom files found, skipping...
starting with no password
[2023-02-18T11:05:17.385Z] info  code-server 4.10.0 ac1fba8bde0c3f29bf6bc27d3d7d75cb2390a7c2
[2023-02-18T11:05:17.390Z] info  Using user-data-dir ~/data
[2023-02-18T11:05:17.410Z] info  Using config file ~/.config/code-server/config.yaml
[2023-02-18T11:05:17.411Z] info  HTTP server listening on http://0.0.0.0:8443/
[2023-02-18T11:05:17.412Z] info    - Authentication is disabled
[2023-02-18T11:05:17.413Z] info    - Not serving HTTPS
[2023-02-18T11:05:17.414Z] info    - Proxying the following domain:
[2023-02-18T11:05:17.415Z] info      - *.code-server.my.domain
[ls.io-init] done.
[11:05:18] 




[11:05:18] Extension host agent started.
[11:05:37] [172.18.0.1][3a4fc3e7][ManagementConnection] New connection established.
[11:05:39] [172.18.0.1][98cec060][ExtensionHostConnection] New connection established.
[11:05:39] [172.18.0.1][98cec060][ExtensionHostConnection] <210> Launched Extension Host Process.
[migrations] started
[migrations] no migrations found
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

setting up sudo access
setting sudo password using SUDO_PASSWORD env var
[custom-init] No custom files found, skipping...
starting with no password
[2023-02-18T11:07:46.457Z] info  code-server 4.10.0 ac1fba8bde0c3f29bf6bc27d3d7d75cb2390a7c2
[2023-02-18T11:07:46.463Z] info  Using user-data-dir ~/data
[2023-02-18T11:07:46.483Z] info  Using config file ~/.config/code-server/config.yaml
[2023-02-18T11:07:46.484Z] info  HTTP server listening on http://0.0.0.0:8443/
[2023-02-18T11:07:46.485Z] info    - Authentication is disabled
[2023-02-18T11:07:46.486Z] info    - Not serving HTTPS
[2023-02-18T11:07:46.487Z] info    - Proxying the following domain:
[2023-02-18T11:07:46.488Z] info      - *.code-server.my.domain
[ls.io-init] done.
[11:07:47] 




[11:07:47] Extension host agent started.
[11:07:55] [172.18.0.1][77e27fbc][ManagementConnection] New connection established.
[11:07:57] [172.18.0.1][f85cb2c8][ExtensionHostConnection] New connection established.
[11:07:57] [172.18.0.1][f85cb2c8][ExtensionHostConnection] <211> Launched Extension Host Process.
[migrations] started
[migrations] no migrations found
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

setting up sudo access
setting sudo password using SUDO_PASSWORD env var
[custom-init] No custom files found, skipping...
starting with no password
[2023-02-18T11:08:50.648Z] info  code-server 4.10.0 ac1fba8bde0c3f29bf6bc27d3d7d75cb2390a7c2
[2023-02-18T11:08:50.653Z] info  Using user-data-dir ~/data
[2023-02-18T11:08:50.670Z] info  Using config file ~/.config/code-server/config.yaml
[2023-02-18T11:08:50.671Z] info  HTTP server listening on http://0.0.0.0:8443/
[2023-02-18T11:08:50.671Z] info    - Authentication is disabled
[2023-02-18T11:08:50.672Z] info    - Not serving HTTPS
[2023-02-18T11:08:50.672Z] info    - Proxying the following domain:
[2023-02-18T11:08:50.673Z] info      - *.code-server.my.domain
[ls.io-init] done.
[11:08:55] 




[11:08:55] Extension host agent started.
[11:12:12] [172.18.0.1][f96bccc5][ManagementConnection] New connection established.
[11:12:14] [172.18.0.1][5bc0d474][ExtensionHostConnection] New connection established.
[11:12:14] [172.18.0.1][5bc0d474][ExtensionHostConnection] <210> Launched Extension Host Process.
[11:15:02] [172.18.0.1][f96bccc5][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[11:15:02] [172.18.0.1][5bc0d474][ExtensionHostConnection] <210> Extension Host Process exited with code: 0, signal: null.
[11:15:03] [172.18.0.1][bc44b1e8][ManagementConnection] New connection established.
[11:15:04] [172.18.0.1][5ed512b5][ExtensionHostConnection] New connection established.
[11:15:05] [172.18.0.1][5ed512b5][ExtensionHostConnection] <678> Launched Extension Host Process.
[11:28:27] [172.18.0.1][5a703937][ManagementConnection] New connection established.
[11:28:29] [172.18.0.1][f60ac7ec][ExtensionHostConnection] New connection established.
[11:28:29] [172.18.0.1][f60ac7ec][ExtensionHostConnection] <2935> Launched Extension Host Process.
[11:28:51] [172.18.0.1][5a703937][ManagementConnection] The client has disconnected, will wait for reconnection 3h before disposing...
[11:29:03] [172.18.0.1][5a703937][ManagementConnection] Another client has connected, will shorten the wait for reconnection 5m before disposing...
[11:29:03] [172.18.0.1][f9cb928d][ManagementConnection] New connection established.
[11:29:05] [172.18.0.1][4197618a][ExtensionHostConnection] New connection established.
[11:29:05] [172.18.0.1][4197618a][ExtensionHostConnection] <3109> Launched Extension Host Process.
[11:31:10] [172.18.0.1][f9cb928d][ManagementConnection] The client has disconnected, will wait for reconnection 3h before disposing...
[11:31:49] [172.18.0.1][f9cb928d][ManagementConnection] Another client has connected, will shorten the wait for reconnection 5m before disposing...
[11:31:49] [172.18.0.1][f9cb928d][ManagementConnection] The client has reconnected.
[11:31:49] [172.18.0.1][4197618a][ExtensionHostConnection] The client has reconnected.
[11:33:41] [172.18.0.1][f9cb928d][ManagementConnection] The client has disconnected, will wait for reconnection 3h before disposing...
[11:33:51] [172.18.0.1][f9cb928d][ManagementConnection] Another client has connected, will shorten the wait for reconnection 5m before disposing...
[11:33:51] [172.18.0.1][4197618a][ExtensionHostConnection] The client has reconnected.
[11:33:51] [172.18.0.1][f9cb928d][ManagementConnection] The client has reconnected.
[11:34:03] [172.18.0.1][f60ac7ec][ExtensionHostConnection] <2935> Extension Host Process exited with code: 0, signal: null.
[11:34:04] [172.18.0.1][5a703937][ManagementConnection] The reconnection short grace time of 5m has expired, so the connection will be disposed.
[11:34:40] [172.18.0.1][f9cb928d][ManagementConnection] The client has disconnected, will wait for reconnection 3h before disposing...
[11:34:42] [172.18.0.1][f9cb928d][ManagementConnection] Another client has connected, will shorten the wait for reconnection 5m before disposing...
[11:34:42] [172.18.0.1][f9cb928d][ManagementConnection] The client has reconnected.
[11:34:42] [172.18.0.1][4197618a][ExtensionHostConnection] The client has reconnected.
[11:34:49] [172.18.0.1][f9cb928d][ManagementConnection] The client has disconnected, will wait for reconnection 3h before disposing...
[11:35:03] [172.18.0.1][f9cb928d][ManagementConnection] Another client has connected, will shorten the wait for reconnection 5m before disposing...
[11:35:03] [172.18.0.1][f9cb928d][ManagementConnection] The client has reconnected.
[11:35:03] [172.18.0.1][4197618a][ExtensionHostConnection] The client has reconnected.
[11:36:18] [172.18.0.1][f9cb928d][ManagementConnection] The client has disconnected, will wait for reconnection 3h before disposing...
[11:36:34] [172.18.0.1][f9cb928d][ManagementConnection] Another client has connected, will shorten the wait for reconnection 5m before disposing...
[11:36:34] [172.18.0.1][4197618a][ExtensionHostConnection] The client has reconnected.
[11:36:34] [172.18.0.1][f9cb928d][ManagementConnection] The client has reconnected.
[11:37:55] [172.18.0.1][f9cb928d][ManagementConnection] The client has disconnected, will wait for reconnection 3h before disposing...
[migrations] started
[migrations] no migrations found
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

setting up sudo access
setting sudo password using SUDO_PASSWORD env var
[custom-init] No custom files found, skipping...
starting with no password
[2023-02-18T11:38:20.924Z] info  code-server 4.10.0 ac1fba8bde0c3f29bf6bc27d3d7d75cb2390a7c2
[2023-02-18T11:38:20.930Z] info  Using user-data-dir ~/data
[2023-02-18T11:38:20.966Z] info  Using config file ~/.config/code-server/config.yaml
[2023-02-18T11:38:20.967Z] info  HTTP server listening on http://0.0.0.0:8443/
[2023-02-18T11:38:20.968Z] info    - Authentication is disabled
[2023-02-18T11:38:20.969Z] info    - Not serving HTTPS
[2023-02-18T11:38:20.970Z] info    - Proxying the following domain:
[2023-02-18T11:38:20.971Z] info      - *.code-server.my.domain
[ls.io-init] done.
[11:38:39] 




[11:38:39] 




[11:38:40] Extension host agent started.
[11:38:40] Extension host agent started.
[11:38:44] [172.18.0.1][b18e9680][ManagementConnection] New connection established.
[11:38:46] [172.18.0.1][19ce606b][ExtensionHostConnection] New connection established.
[11:38:46] [172.18.0.1][19ce606b][ExtensionHostConnection] <233> Launched Extension Host Process.
[11:39:17] [172.18.0.1][b18e9680][ManagementConnection] The client has disconnected, will wait for reconnection 3h before disposing...
[11:48:03] [172.18.0.1][b18e9680][ManagementConnection] Another client has connected, will shorten the wait for reconnection 5m before disposing...
[11:48:03] [172.18.0.1][19ce606b][ExtensionHostConnection] The client has reconnected.
[11:48:03] [172.18.0.1][b18e9680][ManagementConnection] The client has reconnected.
[11:48:54] [172.18.0.1][b18e9680][ManagementConnection] The client has disconnected, will wait for reconnection 3h before disposing...
[11:49:08] [172.18.0.1][b18e9680][ManagementConnection] Another client has connected, will shorten the wait for reconnection 5m before disposing...
[11:49:08] [172.18.0.1][19ce606b][ExtensionHostConnection] The client has reconnected.
[11:49:08] [172.18.0.1][b18e9680][ManagementConnection] The client has reconnected.
```

**Comment by petrm** [comment] 2023-02-27 11:14
I have the same issue. The process in the container is using 100% of one core. There is nothing obvious that might cause this.

**Comment by poundflag** [comment] 2023-02-28 11:10
@tylrtrst How exactly do I revert to an older docker image?

**Comment by petrm** [comment] 2023-03-31 10:13
This issue still persists in all versions above 4.9.1.

**Comment by Roxedus** [comment] 2023-03-31 10:25
We have not been able to reproduce this. I am currently on `code-server: v4.11.0` without issues. 

Getting info rather than just a blanket statement that it doesn't work would hopefully get us closer to resolving this.

**Comment by petrm** [comment] 2023-03-31 15:36
Hi Rodexus,

that's valid feedback. I now upgraded to [4.11.0-ls155] and the problem is gone. It was still there in  [4.11.0-ls154].

**Closed** 2023-06-30 02:40 UTC
Labels: no-issue-activity, closed-issue-activity
