### ISSUE TITLE
Package not found error - arm64

### ISSUE THREAD

**Issue by mwinters-stuff** [linuxserver/docker-code-server#40] opened 2020-11-17 06:33 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Finds package, works

## Current Behavior
Shows error page.

Logs:

```
Error: Cannot find module 'yauzl',
Require stack:,
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15),
  ],,
    at /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:14:10,
    at Function.Module._load (internal/modules/cjs/loader.js:687:27),
    at Module.require (internal/modules/cjs/loader.js:903:19),
    at require (internal/modules/cjs/helpers.js:74:18),
    at t.load (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:17:960),
    at e.load (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:13:941),
    at o (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:31:189),
    at Object.errorback (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:31:313),
    at e.triggerErrorback (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:14:306),
    at ReadFileContext.callback (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:18:342),
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:261:13) {,
  requireStack: [,
    '/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/bootstrap-amd.js',,
    '/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/fork.js',
  phase: 'loading',,
  moduleId: 'yauzl',,
  neededBy: [ 'vs/base/node/zip' ],
}
```

## Steps to Reproduce
Install docker image (rpi4 ubuntu arm64)
Connect to web page.

## Environment
**OS: Ubuntu Server**
**CPU architecture:** arm64
**How docker service was installed:**
Installed, docker repo

## Command used to create docker container (run/create/compose/screenshot)

Compose snippet
```
  code-server:
    image: linuxserver/code-server
    container_name: code-server
    networks:
      - backend
    env_file: 
      - "./conf/code-server.env"
    volumes:
      - ./data/vscode-server/config:/config
      - .:/config/workspace
      - ../.ssh:/config/.ssh
    restart: always
    healthcheck:
      test: pidof node || exit 1
      interval: 120s
      timeout: 10s
      retries: 3
```

## Docker logs
```
code-server           | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
code-server           | [s6-init] ensuring user provided files have correct perms...exited 0.
code-server           | [fix-attrs.d] applying ownership & permissions fixes...
code-server           | [fix-attrs.d] done.
code-server           | [cont-init.d] executing container initialization scripts...
code-server           | [cont-init.d] 01-envfile: executing... 
code-server           | [cont-init.d] 01-envfile: exited 0.
code-server           | [cont-init.d] 10-adduser: executing... 
code-server           | 
code-server           | -------------------------------------
code-server           |           _         ()
code-server           |          | |  ___   _    __
code-server           |          | | / __| | |  /  \ 
code-server           |          | | \__ \ | | | () |
code-server           |          |_| |___/ |_|  \__/
code-server           | 
code-server           | 
code-server           | Brought to you by linuxserver.io
code-server           | -------------------------------------
code-server           | 
code-server           | To support LSIO projects visit:
code-server           | https://www.linuxserver.io/donate/
code-server           | -------------------------------------
code-server           | GID/UID
code-server           | -------------------------------------
code-server           | 
code-server           | User uid:    1001
code-server           | User gid:    1001
code-server           | -------------------------------------
code-server           | 
code-server           | [cont-init.d] 10-adduser: exited 0.
code-server           | [cont-init.d] 30-config: executing... 
code-server           | setting up sudo access
code-server           | adding abc to sudoers
code-server           | setting sudo password
code-server           | Enter new UNIX password: Retype new UNIX password: passwd: password updated successfully
code-server           | [cont-init.d] 30-config: exited 0.
code-server           | [cont-init.d] 99-custom-scripts: executing... 
code-server           | [custom-init] no custom files found exiting...
code-server           | [cont-init.d] 99-custom-scripts: exited 0.
code-server           | [cont-init.d] done.
code-server           | [services.d] starting services
code-server           | [services.d] done.
code-server           | [2020-11-17T04:49:46.390Z] info  Using user-data-dir ~/data
code-server           | [2020-11-17T04:49:46.422Z] info  code-server 3.6.2 9bde62fbd611a7a91c5f327fa43e0d06f1379169
code-server           | [2020-11-17T04:49:46.422Z] info  Using config file ~/.config/code-server/config.yaml
code-server           | [2020-11-17T04:49:46.438Z] info  HTTP server listening on http://0.0.0.0:8443
code-server           | [2020-11-17T04:49:46.438Z] info      - Using password from $PASSWORD
code-server           | [2020-11-17T04:49:46.438Z] info      - To disable use `--auth none`
code-server           | [2020-11-17T04:49:46.439Z] info    - Not serving HTTPS
code-server           | [2020-11-17T04:49:46.439Z] info    - Proxying the following domain:
code-server           | [2020-11-17T04:49:46.440Z] info      - *.www.winters.nz
code-server           | Error: Cannot find module 'semver-umd'
code-server           | Require stack:
code-server           | - /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/bootstrap-amd.js
code-server           | - /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/fork.js
code-server           |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
code-server           |     at Function.Module._load (internal/modules/cjs/loader.js:687:27)
code-server           |     at Module.require (internal/modules/cjs/loader.js:903:19)
code-server           |     at require (internal/modules/cjs/helpers.js:74:18)
code-server           |     at t.load (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:17:960)
code-server           |     at e.load (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:13:941)
code-server           |     at o (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:31:189)
code-server           |     at Object.errorback (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:31:313)
code-server           |     at e.triggerErrorback (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:14:306)
code-server           |     at /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:14:10
code-server           |     at ReadFileContext.callback (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:18:342)
code-server           |     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:261:13) {
code-server           |   code: 'MODULE_NOT_FOUND',
code-server           |   requireStack: [
code-server           |     '/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/bootstrap-amd.js',
code-server           |     '/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/fork.js'
code-server           |   ],
code-server           |   phase: 'loading',
code-server           |   moduleId: 'semver-umd',
code-server           |   neededBy: [
code-server           |     'vs/platform/extensionManagement/node/extensionDownloader',
code-server           |     'vs/workbench/services/extensions/node/extensionPoints',
code-server           |     'vs/platform/extensionManagement/node/extensionsScanner',
code-server           |     'vs/platform/extensionManagement/node/extensionManagementService'
code-server           |   ]
code-server           | }
code-server           | Error: Cannot find module 'applicationinsights'
code-server           | Require stack:
code-server           | - /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/bootstrap-amd.js
code-server           | - /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/fork.js
code-server           |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
code-server           |     at Function.Module._load (internal/modules/cjs/loader.js:687:27)
code-server           |     at Module.require (internal/modules/cjs/loader.js:903:19)
code-server           |     at require (internal/modules/cjs/helpers.js:74:18)
code-server           |     at t.load (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:17:960)
code-server           |     at e.load (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:13:941)
code-server           |     at o (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:31:189)
code-server           |     at Object.errorback (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:31:313)
code-server           |     at e.triggerErrorback (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:14:306)
code-server           |     at /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:14:10
code-server           |     at ReadFileContext.callback (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:18:342)
code-server           |     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:261:13) {
code-server           |   code: 'MODULE_NOT_FOUND',
code-server           |   requireStack: [
code-server           |     '/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/bootstrap-amd.js',
code-server           |     '/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/fork.js'
code-server           |   ],
code-server           |   phase: 'loading',
code-server           |   moduleId: 'applicationinsights',
code-server           |   neededBy: [ 'vs/platform/telemetry/node/appInsightsAppender' ]
code-server           | }
code-server           | Error: Cannot find module '@coder/node-browser'
code-server           | Require stack:
code-server           | - /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/bootstrap-amd.js
code-server           | - /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/fork.js
code-server           |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
code-server           |     at Function.Module._load (internal/modules/cjs/loader.js:687:27)
code-server           |     at Module.require (internal/modules/cjs/loader.js:903:19)
code-server           |     at require (internal/modules/cjs/helpers.js:74:18)
code-server           |     at t.load (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:17:960)
code-server           |     at e.load (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:13:941)
code-server           |     at o (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:31:189)
code-server           |     at Object.errorback (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:31:313)
code-server           |     at e.triggerErrorback (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:14:306)
code-server           |     at /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:14:10
code-server           |     at ReadFileContext.callback (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:18:342)
code-server           |     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:261:13) {
code-server           |   code: 'MODULE_NOT_FOUND',
code-server           |   requireStack: [
code-server           |     '/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/bootstrap-amd.js',
code-server           |     '/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/fork.js'
code-server           |   ],
code-server           |   phase: 'loading',
code-server           |   moduleId: '@coder/node-browser',
code-server           |   neededBy: [ 'vs/server/node/channel' ]
code-server           | }
code-server           | Error: Cannot find module 'yazl'
code-server           | Require stack:
code-server           | - /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/bootstrap-amd.js
code-server           | - /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/fork.js
code-server           |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
code-server           |     at Function.Module._load (internal/modules/cjs/loader.js:687:27)
code-server           |     at Module.require (internal/modules/cjs/loader.js:903:19)
code-server           |     at require (internal/modules/cjs/helpers.js:74:18)
code-server           |     at t.load (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:17:960)
code-server           |     at e.load (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:13:941)
code-server           |     at o (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:31:189)
code-server           |     at Object.errorback (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:31:313)
code-server           |     at e.triggerErrorback (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:14:306)
code-server           |     at /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:14:10
code-server           |     at ReadFileContext.callback (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:18:342)
code-server           |     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:261:13) {
code-server           |   code: 'MODULE_NOT_FOUND',
code-server           |   requireStack: [
code-server           |     '/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/bootstrap-amd.js',
code-server           |     '/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/fork.js'
code-server           |   ],
code-server           |   phase: 'loading',
code-server           |   moduleId: 'yazl',
code-server           |   neededBy: [ 'vs/base/node/zip' ]
code-server           | }
code-server           | Error: Cannot find module 'yauzl'
code-server           | Require stack:
code-server           | - /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/bootstrap-amd.js
code-server           | - /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/fork.js
code-server           |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
code-server           |     at Function.Module._load (internal/modules/cjs/loader.js:687:27)
code-server           |     at Module.require (internal/modules/cjs/loader.js:903:19)
code-server           |     at require (internal/modules/cjs/helpers.js:74:18)
code-server           |     at t.load (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:17:960)
code-server           |     at e.load (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:13:941)
code-server           |     at o (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:31:189)
code-server           |     at Object.errorback (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:31:313)
code-server           |     at e.triggerErrorback (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:14:306)
code-server           |     at /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:14:10
code-server           |     at ReadFileContext.callback (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:18:342)
code-server           |     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:261:13) {
code-server           |   code: 'MODULE_NOT_FOUND',
code-server           |   requireStack: [
code-server           |     '/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/bootstrap-amd.js',
code-server           |     '/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/fork.js'
code-server           |   ],
code-server           |   phase: 'loading',
code-server           |   moduleId: 'yauzl',
code-server           |   neededBy: [ 'vs/base/node/zip' ]
code-server           | }
code-server           | [2020-11-17T04:52:07.850Z] error VS Code exited unexpectedly with code 0
```

**Comment by mwinters-stuff** [comment] 2020-11-17 20:39
build v3.6.2-ls54 is the last one that worked.

**Comment by aptalca** [comment] 2020-11-17 20:45
I just checked our ci test builds and they seem to have the same issue on arm64. If 3.6.2-ls54 works but not the latest, it could be due to a dependency package update, maybe node. We'll look into it.

**Comment by aptalca** [comment] 2020-11-17 20:48
Looks like this is what changed between ls54 and ls55: https://github.com/linuxserver/docker-code-server/commit/29ae7551a63a0c6e1d7e328c5ee48609a70b9460
Hmm, udev/systemd version 43 was recently pulled due to issues, I wonder if that's related.

**Comment by aptalca** [comment] 2020-11-17 21:31
yup, confirmed issue is due to udev, pushing a new build

**Comment by aptalca** [comment] 2020-11-18 03:02
Fixed in the latest push

**Comment by jarfil** [comment] 2020-11-19 07:16
This issue seems to be back in ls58. I've checked the following from Docker Hub:

* v3.6.2-ls54 - ok
* v3.6.2-ls55 - error 500
* v3.6.2-ls56 - error 500
* v3.7.1-ls57 - ok
* v3.7.1-ls58 - error 500

**Comment by aptalca** [comment] 2020-11-19 18:05
Yeah, we have 5 arm64 builders and one (or more) were putting out non-functional images. I'm assuming it was due to the old baseimage with the faulty udev, but haven't had time to investigate.

The latest build up now is working, so I'll monitor and if the issue comes back, we'll look into it further.

**Comment by aptalca** [comment] 2020-11-24 20:30
Looks like we're still having this issue as the latest build exhibits the same problem: https://ci-tests.linuxserver.io/linuxserver/code-server/v3.7.3-ls59/index.html

Some of our builders are pushing out broken images and we're still looking into it.

**Closed** 2020-11-25 05:19 UTC
